// Code generated by scripts/generate_skill_config_contract.go; DO NOT EDIT.
// 此文件由 scripts/generate_skill_config_contract.go 生成；请勿手工编辑。

//go:generate go run ./scripts/generate_skill_config_contract.go

package luaskills

// SkillPackageConfigType is the stable wire type of one declared package configuration item.
// SkillPackageConfigType 是单个已声明技能包配置项的稳定线协议类型。
type SkillPackageConfigType string

const (
	// SkillPackageConfigTypeInteger identifies package-configuration type "integer".
	// SkillPackageConfigTypeInteger 标识技能包配置类型 "integer"。
	SkillPackageConfigTypeInteger SkillPackageConfigType = "integer"
	// SkillPackageConfigTypeString identifies package-configuration type "string".
	// SkillPackageConfigTypeString 标识技能包配置类型 "string"。
	SkillPackageConfigTypeString SkillPackageConfigType = "string"
	// SkillPackageConfigTypeFloat identifies package-configuration type "float".
	// SkillPackageConfigTypeFloat 标识技能包配置类型 "float"。
	SkillPackageConfigTypeFloat SkillPackageConfigType = "float"
	// SkillPackageConfigTypeEnum identifies package-configuration type "enum".
	// SkillPackageConfigTypeEnum 标识技能包配置类型 "enum"。
	SkillPackageConfigTypeEnum SkillPackageConfigType = "enum"
	// SkillPackageConfigTypeBoolean identifies package-configuration type "boolean".
	// SkillPackageConfigTypeBoolean 标识技能包配置类型 "boolean"。
	SkillPackageConfigTypeBoolean SkillPackageConfigType = "boolean"
)

// SkillPackageConfigItemState identifies the unambiguous runtime state of one declared item.
// SkillPackageConfigItemState 标识单个已声明项的无歧义运行时状态。
type SkillPackageConfigItemState string

const (
	// SkillPackageConfigItemStateUnset identifies package-configuration state "unset".
	// SkillPackageConfigItemStateUnset 标识技能包配置状态 "unset"。
	SkillPackageConfigItemStateUnset SkillPackageConfigItemState = "unset"
	// SkillPackageConfigItemStateMissing identifies package-configuration state "missing".
	// SkillPackageConfigItemStateMissing 标识技能包配置状态 "missing"。
	SkillPackageConfigItemStateMissing SkillPackageConfigItemState = "missing"
	// SkillPackageConfigItemStateDefault identifies package-configuration state "default".
	// SkillPackageConfigItemStateDefault 标识技能包配置状态 "default"。
	SkillPackageConfigItemStateDefault SkillPackageConfigItemState = "default"
	// SkillPackageConfigItemStateConfigured identifies package-configuration state "configured".
	// SkillPackageConfigItemStateConfigured 标识技能包配置状态 "configured"。
	SkillPackageConfigItemStateConfigured SkillPackageConfigItemState = "configured"
	// SkillPackageConfigItemStateInvalid identifies package-configuration state "invalid".
	// SkillPackageConfigItemStateInvalid 标识技能包配置状态 "invalid"。
	SkillPackageConfigItemStateInvalid SkillPackageConfigItemState = "invalid"
)

// SkillPackageConfigDescribeMode identifies one declaration discovery mode.
// SkillPackageConfigDescribeMode 标识单个声明发现模式。
type SkillPackageConfigDescribeMode string

const (
	// SkillPackageConfigDescribeModeEffective identifies package-configuration discovery mode "effective".
	// SkillPackageConfigDescribeModeEffective 标识技能包配置发现模式 "effective"。
	SkillPackageConfigDescribeModeEffective SkillPackageConfigDescribeMode = "effective"
	// SkillPackageConfigDescribeModeInstalled identifies package-configuration discovery mode "installed".
	// SkillPackageConfigDescribeModeInstalled 标识技能包配置发现模式 "installed"。
	SkillPackageConfigDescribeModeInstalled SkillPackageConfigDescribeMode = "installed"
)

// SkillConfigStoreScope identifies one routed configuration store.
// SkillConfigStoreScope 标识单个路由后的配置存储。
type SkillConfigStoreScope string

const (
	// SkillConfigStoreScopeSkills identifies package-configuration store scope "skills".
	// SkillConfigStoreScopeSkills 标识技能包配置存储作用域 "skills"。
	SkillConfigStoreScopeSkills SkillConfigStoreScope = "skills"
	// SkillConfigStoreScopeSystemSkills identifies package-configuration store scope "system-skills".
	// SkillConfigStoreScopeSystemSkills 标识技能包配置存储作用域 "system-skills"。
	SkillConfigStoreScopeSystemSkills SkillConfigStoreScope = "system-skills"
)

// SkillConfigErrorCode identifies one stable package-configuration failure.
// SkillConfigErrorCode 标识单个稳定技能包配置失败。
type SkillConfigErrorCode string

const (
	// SkillConfigErrorCodeAtomicReplaceFailed identifies package-configuration error "CONFIG_ATOMIC_REPLACE_FAILED".
	// SkillConfigErrorCodeAtomicReplaceFailed 标识技能包配置错误 "CONFIG_ATOMIC_REPLACE_FAILED"。
	SkillConfigErrorCodeAtomicReplaceFailed SkillConfigErrorCode = "CONFIG_ATOMIC_REPLACE_FAILED"
	// SkillConfigErrorCodeBatchArgumentConflict identifies package-configuration error "CONFIG_BATCH_ARGUMENT_CONFLICT".
	// SkillConfigErrorCodeBatchArgumentConflict 标识技能包配置错误 "CONFIG_BATCH_ARGUMENT_CONFLICT"。
	SkillConfigErrorCodeBatchArgumentConflict SkillConfigErrorCode = "CONFIG_BATCH_ARGUMENT_CONFLICT"
	// SkillConfigErrorCodeBatchEmpty identifies package-configuration error "CONFIG_BATCH_EMPTY".
	// SkillConfigErrorCodeBatchEmpty 标识技能包配置错误 "CONFIG_BATCH_EMPTY"。
	SkillConfigErrorCodeBatchEmpty SkillConfigErrorCode = "CONFIG_BATCH_EMPTY"
	// SkillConfigErrorCodeBatchTooLarge identifies package-configuration error "CONFIG_BATCH_TOO_LARGE".
	// SkillConfigErrorCodeBatchTooLarge 标识技能包配置错误 "CONFIG_BATCH_TOO_LARGE"。
	SkillConfigErrorCodeBatchTooLarge SkillConfigErrorCode = "CONFIG_BATCH_TOO_LARGE"
	// SkillConfigErrorCodeDeclarationInvalid identifies package-configuration error "CONFIG_DECLARATION_INVALID".
	// SkillConfigErrorCodeDeclarationInvalid 标识技能包配置错误 "CONFIG_DECLARATION_INVALID"。
	SkillConfigErrorCodeDeclarationInvalid SkillConfigErrorCode = "CONFIG_DECLARATION_INVALID"
	// SkillConfigErrorCodeEnumValueInvalid identifies package-configuration error "CONFIG_ENUM_VALUE_INVALID".
	// SkillConfigErrorCodeEnumValueInvalid 标识技能包配置错误 "CONFIG_ENUM_VALUE_INVALID"。
	SkillConfigErrorCodeEnumValueInvalid SkillConfigErrorCode = "CONFIG_ENUM_VALUE_INVALID"
	// SkillConfigErrorCodeEventCursorExpired identifies package-configuration error "CONFIG_EVENT_CURSOR_EXPIRED".
	// SkillConfigErrorCodeEventCursorExpired 标识技能包配置错误 "CONFIG_EVENT_CURSOR_EXPIRED"。
	SkillConfigErrorCodeEventCursorExpired SkillConfigErrorCode = "CONFIG_EVENT_CURSOR_EXPIRED"
	// SkillConfigErrorCodeEventCursorInvalid identifies package-configuration error "CONFIG_EVENT_CURSOR_INVALID".
	// SkillConfigErrorCodeEventCursorInvalid 标识技能包配置错误 "CONFIG_EVENT_CURSOR_INVALID"。
	SkillConfigErrorCodeEventCursorInvalid SkillConfigErrorCode = "CONFIG_EVENT_CURSOR_INVALID"
	// SkillConfigErrorCodeFileTooLarge identifies package-configuration error "CONFIG_FILE_TOO_LARGE".
	// SkillConfigErrorCodeFileTooLarge 标识技能包配置错误 "CONFIG_FILE_TOO_LARGE"。
	SkillConfigErrorCodeFileTooLarge SkillConfigErrorCode = "CONFIG_FILE_TOO_LARGE"
	// SkillConfigErrorCodeFormatInvalid identifies package-configuration error "CONFIG_FORMAT_INVALID".
	// SkillConfigErrorCodeFormatInvalid 标识技能包配置错误 "CONFIG_FORMAT_INVALID"。
	SkillConfigErrorCodeFormatInvalid SkillConfigErrorCode = "CONFIG_FORMAT_INVALID"
	// SkillConfigErrorCodeFormatVersionUnsupported identifies package-configuration error "CONFIG_FORMAT_VERSION_UNSUPPORTED".
	// SkillConfigErrorCodeFormatVersionUnsupported 标识技能包配置错误 "CONFIG_FORMAT_VERSION_UNSUPPORTED"。
	SkillConfigErrorCodeFormatVersionUnsupported SkillConfigErrorCode = "CONFIG_FORMAT_VERSION_UNSUPPORTED"
	// SkillConfigErrorCodeKeyInvalid identifies package-configuration error "CONFIG_KEY_INVALID".
	// SkillConfigErrorCodeKeyInvalid 标识技能包配置错误 "CONFIG_KEY_INVALID"。
	SkillConfigErrorCodeKeyInvalid SkillConfigErrorCode = "CONFIG_KEY_INVALID"
	// SkillConfigErrorCodeKeyUndeclared identifies package-configuration error "CONFIG_KEY_UNDECLARED".
	// SkillConfigErrorCodeKeyUndeclared 标识技能包配置错误 "CONFIG_KEY_UNDECLARED"。
	SkillConfigErrorCodeKeyUndeclared SkillConfigErrorCode = "CONFIG_KEY_UNDECLARED"
	// SkillConfigErrorCodeLockFailed identifies package-configuration error "CONFIG_LOCK_FAILED".
	// SkillConfigErrorCodeLockFailed 标识技能包配置错误 "CONFIG_LOCK_FAILED"。
	SkillConfigErrorCodeLockFailed SkillConfigErrorCode = "CONFIG_LOCK_FAILED"
	// SkillConfigErrorCodeLockTimeout identifies package-configuration error "CONFIG_LOCK_TIMEOUT".
	// SkillConfigErrorCodeLockTimeout 标识技能包配置错误 "CONFIG_LOCK_TIMEOUT"。
	SkillConfigErrorCodeLockTimeout SkillConfigErrorCode = "CONFIG_LOCK_TIMEOUT"
	// SkillConfigErrorCodePackageNotFound identifies package-configuration error "CONFIG_PACKAGE_NOT_FOUND".
	// SkillConfigErrorCodePackageNotFound 标识技能包配置错误 "CONFIG_PACKAGE_NOT_FOUND"。
	SkillConfigErrorCodePackageNotFound SkillConfigErrorCode = "CONFIG_PACKAGE_NOT_FOUND"
	// SkillConfigErrorCodePathInvalid identifies package-configuration error "CONFIG_PATH_INVALID".
	// SkillConfigErrorCodePathInvalid 标识技能包配置错误 "CONFIG_PATH_INVALID"。
	SkillConfigErrorCodePathInvalid SkillConfigErrorCode = "CONFIG_PATH_INVALID"
	// SkillConfigErrorCodePathUnavailable identifies package-configuration error "CONFIG_PATH_UNAVAILABLE".
	// SkillConfigErrorCodePathUnavailable 标识技能包配置错误 "CONFIG_PATH_UNAVAILABLE"。
	SkillConfigErrorCodePathUnavailable SkillConfigErrorCode = "CONFIG_PATH_UNAVAILABLE"
	// SkillConfigErrorCodeReloadFailed identifies package-configuration error "CONFIG_RELOAD_FAILED".
	// SkillConfigErrorCodeReloadFailed 标识技能包配置错误 "CONFIG_RELOAD_FAILED"。
	SkillConfigErrorCodeReloadFailed SkillConfigErrorCode = "CONFIG_RELOAD_FAILED"
	// SkillConfigErrorCodeResponseTooLarge identifies package-configuration error "CONFIG_RESPONSE_TOO_LARGE".
	// SkillConfigErrorCodeResponseTooLarge 标识技能包配置错误 "CONFIG_RESPONSE_TOO_LARGE"。
	SkillConfigErrorCodeResponseTooLarge SkillConfigErrorCode = "CONFIG_RESPONSE_TOO_LARGE"
	// SkillConfigErrorCodeRevisionConflict identifies package-configuration error "CONFIG_REVISION_CONFLICT".
	// SkillConfigErrorCodeRevisionConflict 标识技能包配置错误 "CONFIG_REVISION_CONFLICT"。
	SkillConfigErrorCodeRevisionConflict SkillConfigErrorCode = "CONFIG_REVISION_CONFLICT"
	// SkillConfigErrorCodeRevisionExhausted identifies package-configuration error "CONFIG_REVISION_EXHAUSTED".
	// SkillConfigErrorCodeRevisionExhausted 标识技能包配置错误 "CONFIG_REVISION_EXHAUSTED"。
	SkillConfigErrorCodeRevisionExhausted SkillConfigErrorCode = "CONFIG_REVISION_EXHAUSTED"
	// SkillConfigErrorCodeRevisionInvalid identifies package-configuration error "CONFIG_REVISION_INVALID".
	// SkillConfigErrorCodeRevisionInvalid 标识技能包配置错误 "CONFIG_REVISION_INVALID"。
	SkillConfigErrorCodeRevisionInvalid SkillConfigErrorCode = "CONFIG_REVISION_INVALID"
	// SkillConfigErrorCodeRevisionRegression identifies package-configuration error "CONFIG_REVISION_REGRESSION".
	// SkillConfigErrorCodeRevisionRegression 标识技能包配置错误 "CONFIG_REVISION_REGRESSION"。
	SkillConfigErrorCodeRevisionRegression SkillConfigErrorCode = "CONFIG_REVISION_REGRESSION"
	// SkillConfigErrorCodeSnapshotUnavailable identifies package-configuration error "CONFIG_SNAPSHOT_UNAVAILABLE".
	// SkillConfigErrorCodeSnapshotUnavailable 标识技能包配置错误 "CONFIG_SNAPSHOT_UNAVAILABLE"。
	SkillConfigErrorCodeSnapshotUnavailable SkillConfigErrorCode = "CONFIG_SNAPSHOT_UNAVAILABLE"
	// SkillConfigErrorCodeValidatorFailed identifies package-configuration error "CONFIG_VALIDATOR_FAILED".
	// SkillConfigErrorCodeValidatorFailed 标识技能包配置错误 "CONFIG_VALIDATOR_FAILED"。
	SkillConfigErrorCodeValidatorFailed SkillConfigErrorCode = "CONFIG_VALIDATOR_FAILED"
	// SkillConfigErrorCodeValidatorLimitExceeded identifies package-configuration error "CONFIG_VALIDATOR_LIMIT_EXCEEDED".
	// SkillConfigErrorCodeValidatorLimitExceeded 标识技能包配置错误 "CONFIG_VALIDATOR_LIMIT_EXCEEDED"。
	SkillConfigErrorCodeValidatorLimitExceeded SkillConfigErrorCode = "CONFIG_VALIDATOR_LIMIT_EXCEEDED"
	// SkillConfigErrorCodeValidatorTimeout identifies package-configuration error "CONFIG_VALIDATOR_TIMEOUT".
	// SkillConfigErrorCodeValidatorTimeout 标识技能包配置错误 "CONFIG_VALIDATOR_TIMEOUT"。
	SkillConfigErrorCodeValidatorTimeout SkillConfigErrorCode = "CONFIG_VALIDATOR_TIMEOUT"
	// SkillConfigErrorCodeValidatorUnavailable identifies package-configuration error "CONFIG_VALIDATOR_UNAVAILABLE".
	// SkillConfigErrorCodeValidatorUnavailable 标识技能包配置错误 "CONFIG_VALIDATOR_UNAVAILABLE"。
	SkillConfigErrorCodeValidatorUnavailable SkillConfigErrorCode = "CONFIG_VALIDATOR_UNAVAILABLE"
	// SkillConfigErrorCodeValueOutOfRange identifies package-configuration error "CONFIG_VALUE_OUT_OF_RANGE".
	// SkillConfigErrorCodeValueOutOfRange 标识技能包配置错误 "CONFIG_VALUE_OUT_OF_RANGE"。
	SkillConfigErrorCodeValueOutOfRange SkillConfigErrorCode = "CONFIG_VALUE_OUT_OF_RANGE"
	// SkillConfigErrorCodeValueTooLong identifies package-configuration error "CONFIG_VALUE_TOO_LONG".
	// SkillConfigErrorCodeValueTooLong 标识技能包配置错误 "CONFIG_VALUE_TOO_LONG"。
	SkillConfigErrorCodeValueTooLong SkillConfigErrorCode = "CONFIG_VALUE_TOO_LONG"
	// SkillConfigErrorCodeValueTypeInvalid identifies package-configuration error "CONFIG_VALUE_TYPE_INVALID".
	// SkillConfigErrorCodeValueTypeInvalid 标识技能包配置错误 "CONFIG_VALUE_TYPE_INVALID"。
	SkillConfigErrorCodeValueTypeInvalid SkillConfigErrorCode = "CONFIG_VALUE_TYPE_INVALID"
	// SkillConfigErrorCodeWatcherFailed identifies package-configuration error "CONFIG_WATCHER_FAILED".
	// SkillConfigErrorCodeWatcherFailed 标识技能包配置错误 "CONFIG_WATCHER_FAILED"。
	SkillConfigErrorCodeWatcherFailed SkillConfigErrorCode = "CONFIG_WATCHER_FAILED"
)

// SkillConfigContractVersion is the package-configuration wire contract version.
// SkillConfigContractVersion 是技能包配置线协议版本。
const SkillConfigContractVersion = 1

// SkillConfigMaximumSafeInteger is the largest exactly representable integer shared by every supported SDK.
// SkillConfigMaximumSafeInteger 是所有受支持 SDK 共同精确表示的最大整数。
const SkillConfigMaximumSafeInteger int64 = 9007199254740991

// SkillConfigMaximumEventPollLimit is the largest event page accepted by the core contract.
// SkillConfigMaximumEventPollLimit 是核心契约允许的最大事件分页大小。
const SkillConfigMaximumEventPollLimit uint64 = 1024

// SkillPackageConfigTypes contains the stable declared scalar types in contract order.
// SkillPackageConfigTypes 按契约顺序包含稳定的已声明标量类型。
var SkillPackageConfigTypes = []SkillPackageConfigType{
	SkillPackageConfigTypeInteger,
	SkillPackageConfigTypeString,
	SkillPackageConfigTypeFloat,
	SkillPackageConfigTypeEnum,
	SkillPackageConfigTypeBoolean,
}

// SkillPackageConfigFormats contains the stable host rendering formats in contract order.
// SkillPackageConfigFormats 按契约顺序包含稳定的宿主渲染格式。
var SkillPackageConfigFormats = []string{
	"text",
	"password",
	"uri",
	"path",
	"file",
	"directory",
	"multiline",
}

// SkillPackageConfigStates contains the stable effective-value states in contract order.
// SkillPackageConfigStates 按契约顺序包含稳定的有效值状态。
var SkillPackageConfigStates = []SkillPackageConfigItemState{
	SkillPackageConfigItemStateUnset,
	SkillPackageConfigItemStateMissing,
	SkillPackageConfigItemStateDefault,
	SkillPackageConfigItemStateConfigured,
	SkillPackageConfigItemStateInvalid,
}

// SkillPackageConfigDescribeModes contains stable declaration discovery modes in contract order.
// SkillPackageConfigDescribeModes 按契约顺序包含稳定的声明发现模式。
var SkillPackageConfigDescribeModes = []SkillPackageConfigDescribeMode{
	SkillPackageConfigDescribeModeEffective,
	SkillPackageConfigDescribeModeInstalled,
}

// SkillConfigStoreScopes contains stable routed configuration stores in contract order.
// SkillConfigStoreScopes 按契约顺序包含稳定的路由配置存储作用域。
var SkillConfigStoreScopes = []SkillConfigStoreScope{
	SkillConfigStoreScopeSkills,
	SkillConfigStoreScopeSystemSkills,
}

// SkillConfigErrorCodes contains stable package-configuration errors in contract order.
// SkillConfigErrorCodes 按契约顺序包含稳定的技能包配置错误码。
var SkillConfigErrorCodes = []SkillConfigErrorCode{
	SkillConfigErrorCodeAtomicReplaceFailed,
	SkillConfigErrorCodeBatchArgumentConflict,
	SkillConfigErrorCodeBatchEmpty,
	SkillConfigErrorCodeBatchTooLarge,
	SkillConfigErrorCodeDeclarationInvalid,
	SkillConfigErrorCodeEnumValueInvalid,
	SkillConfigErrorCodeEventCursorExpired,
	SkillConfigErrorCodeEventCursorInvalid,
	SkillConfigErrorCodeFileTooLarge,
	SkillConfigErrorCodeFormatInvalid,
	SkillConfigErrorCodeFormatVersionUnsupported,
	SkillConfigErrorCodeKeyInvalid,
	SkillConfigErrorCodeKeyUndeclared,
	SkillConfigErrorCodeLockFailed,
	SkillConfigErrorCodeLockTimeout,
	SkillConfigErrorCodePackageNotFound,
	SkillConfigErrorCodePathInvalid,
	SkillConfigErrorCodePathUnavailable,
	SkillConfigErrorCodeReloadFailed,
	SkillConfigErrorCodeResponseTooLarge,
	SkillConfigErrorCodeRevisionConflict,
	SkillConfigErrorCodeRevisionExhausted,
	SkillConfigErrorCodeRevisionInvalid,
	SkillConfigErrorCodeRevisionRegression,
	SkillConfigErrorCodeSnapshotUnavailable,
	SkillConfigErrorCodeValidatorFailed,
	SkillConfigErrorCodeValidatorLimitExceeded,
	SkillConfigErrorCodeValidatorTimeout,
	SkillConfigErrorCodeValidatorUnavailable,
	SkillConfigErrorCodeValueOutOfRange,
	SkillConfigErrorCodeValueTooLong,
	SkillConfigErrorCodeValueTypeInvalid,
	SkillConfigErrorCodeWatcherFailed,
}
